Doc api
prixite/saas-erp pull request #293
Opened 2022-11-18 08:32 UTC by aftab76ahmad76

Updated docs api
Todo: link an issue no

2022-11-18 11:32 UTC, h-yaqub requested changes

2022-11-18 11:32 UTC, h-yaqub commented on app/views/api.py
> +        employee = models.Employee.objects.filter(id=kwargs.get("pk")).exists()
```suggestion
        try:
             employee = models.Employee.objects.get(id=kwargs.get("pk"))
        except models.Employee.DoesNotExist:
             return Response(
                 data={"detail": "Employee does not exist"},
                 status=status.HTTP_404_NOT_FOUND,
             )
```

2022-11-18 11:50 UTC, h-yaqub requested changes

2022-11-18 11:50 UTC, h-yaqub commented on app/views/api.py
> +                    "type": type,
```suggestion
                    "type": type if type else "Others",
```

2022-11-18 11:54 UTC, h-yaqub requested changes

2022-11-18 11:55 UTC, h-yaqub requested changes

2022-11-19 09:46 UTC, aftab76ahmad76 commented on app/views/api.py
> +                    "type": type if type else "Others",
Can't access type.name here..type here is just json int value

2022-11-23 07:49 UTC, h-yaqub approved these changes

2022-11-23 07:50 UTC, merged