Allowed modules
prixite/saas-erp pull request #348
Opened 2022-12-05 10:53 UTC by aftab76ahmad76

Added allowed modules field in me api & fixed image domain bug

2022-12-05 11:00 UTC, getalihassan requested changes

2022-12-05 11:00 UTC, getalihassan commented on app/serializers.py
> +        allowed_modules = []
why not just make it set 
allowed_modules = {}
allowed_modules.add(module.slug)

2022-12-05 11:00 UTC, getalihassan commented on frontend/src/store/reducers/generated.ts
> +export type ApiFlagsRetrieveApiResponse = unknown;
why flags response is Unknown?

2022-12-06 05:53 UTC, h-yaqub approved these changes

2022-12-06 08:09 UTC, closed without merging