add availability api.
prixite/saas-erp pull request #567
Opened 2023-02-28 10:54 UTC by sprixite

2023-03-02 07:31 UTC, h-yaqub requested changes

2023-03-02 07:31 UTC, h-yaqub commented on app/views/mixins.py
> +        date = self.request.query_params.get("date")
```suggestion
        interval = self.request.query_params.get("interval")
```

2023-03-02 07:31 UTC, h-yaqub commented on app/views/mixins.py
> +            print("ok")
```suggestion
```

2023-03-02 07:31 UTC, h-yaqub commented on app/views/mixins.py
> +        if date == "weekly":
```suggestion
        if interval == "weekly":
```

2023-03-02 07:31 UTC, h-yaqub commented on app/views/mixins.py
> +            start_date_str = end_date_str - timedelta(days=7)
We are asked to calculate the last week days. If above ran on Tuesday of current week, Monday of last week will be missed. Try below code:
```suggestion
            some_day_last_week = timezone.now().date() - timedelta(days=7)
            monday_of_last_week = some_day_last_week - timedelta(days=(some_day_last_week.isocalendar()[2] - 1))
            monday_of_this_week = monday_of_last_week + timedelta(days=7)
```

2023-03-03 10:47 UTC, umairjameelprixite approved these changes

2023-03-03 10:50 UTC, merged